### PR TITLE
#602: include client id in guest checkout api

### LINKED ISSUE #602: Add `X-UID` header for with value `partner_xxx` for the all guest checkout calls... (currently guest checkout is not working)

### PR DESCRIPTION
**Pull request by hani-ibrahim**
fixes #602 
+
submit button title

### CODE REVIEW

File: AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift [hunk 1]
```diff
@@ -147,20 +147,23 @@ extension AtlasAPIClient {
     public func createGuestOrder(request: GuestOrderRequest, completion: @escaping GuestOrderCompletion) {
         let endpoint = CreateGuestOrderEndpoint(serviceURL: config.checkoutGatewayURL,
```
Comment (bonkey) [inline AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift]: Maybe create `CreateGuestOrderEndpoint.init(config:parameters:)` instead?

File: AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift [hunk 2]
```diff
@@ -147,20 +147,23 @@ extension AtlasAPIClient {
...
                                                 parameters: request.toJSON(),
-                                                salesChannel: config.salesChannel.identifier)
+                                                salesChannel: config.salesChannel.identifier,
+                                                clientId: config.clientId)
         fetch(from: endpoint, completion: completion)
     }
 
     public func guestCheckoutPaymentSelectionURL(request: GuestPaymentSelectionRequest, completion: @escaping URLCompletion) {
         let endpoint = CreateGuestOrderEndpoint(serviceURL: config.checkoutGatewayURL,
```
Comment (bonkey) [inline AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift]: Ditto. Maybe create `CreateGuestOrderEndpoint.init(config:parameters:)` instead?

File: AtlasSDK/AtlasSDK/Endpoints/GetGuestCheckoutEndpoint.swift [hunk 3]
```diff
@@ -2,13 +2,14 @@
 //  Copyright © 2016 Zalando SE. All rights reserved.
 //
 
-struct GetGuestCheckoutEndpoint: ConfigurableEndpoint, SalesChannelEndpoint {
```
Comment (bonkey) [inline AtlasSDK/AtlasSDK/Endpoints/GetGuestCheckoutEndpoint.swift]: How about adding new protocol for X-UID instead of removing this here?

File: AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift (hunk 1 above)
Comment (hani-ibrahim) [inline AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift]: I don't know but none of our Endpoints has init method, it will be odd for this one?

Comment (bonkey) [inline AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift]: Nah, why odd. They don't have to be identical unless the odds are super strange.

Comment (hani-ibrahim) [inline AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift]: well, if config is shared we will not have to do all this 😛

**Comment by hani-ibrahim** [comment]
:+1:

**Comment by bonkey** [comment]
👍
